### ISSUE TITLE
Get Element on Linux weird UI

### ISSUE THREAD

**Issue by SimonBrandner** [vector-im/element.io#10]
**Describe the bug**
The `Get Element on Linux` UI is weird. It almost looks as if there were scroll bars.

**To Reproduce**

1. Go to [Get started](https://element.io/get-started)
2. Click on `Also available on Linux`

**Screenshots**

![Screenshot_20210116_151926](https://user-images.githubusercontent.com/25768714/104814300-7293b000-580e-11eb-9485-d8e9ed011109.png)

**Info**

On Firefox, Chromium and Chrome on desktop

**Comment by uhoreg** [comment]
Looks like this was fixed in the new site
