### ISSUE TITLE
desktop client version 1.7.20 olm version: 3.2.1 routes output sound to wrong device

### ISSUE THREAD

**Issue by sergstesh** [vector-im/element.io#12]
This bug report is about element.io desktop client, but the problem and the environment (OS, desktop environment) is exactly the same as https://github.com/telegramdesktop/tdesktop/issues/10411 . The bug report is about Telegram desktop client, but the phenomenon is the same.

**Comment by SimonBrandner** [comment]
@sergstesh, any Element Web/Desktop issues should be reported [here](https://github.com/vector-im/element-web)

This is a repo for the website _not_ the app itself
