### ISSUE TITLE
Add underline to "get for linux" and "get on f-droid" links.

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element.io#16]
![image](https://user-images.githubusercontent.com/22740616/112686193-ed63f180-8e75-11eb-8163-699352bd9e7c.png)
![image](https://user-images.githubusercontent.com/22740616/112686206-f2c13c00-8e75-11eb-971b-3523fd359771.png)

These are clickable, but they look like non-clickable subtitles.

This is what i mean, somewhat;
![image](https://user-images.githubusercontent.com/22740616/112686629-8d217f80-8e76-11eb-8123-80aa1070a532.png)

```css
    text-decoration: underline;
    text-decoration-color: rgb(10, 151, 111);
    text-decoration-thickness: 3px;
    text-underline-offset: 2px;
```
([can-i-use for `text-underline-offset`](https://caniuse.com/?search=text-underline-offset))

**Comment by turt2live** [comment]
This happened
