### ISSUE TITLE
Improve the Linux onboarding process

### ISSUE THREAD

**Issue by elsiehupp** [vector-im/element.io#18]
> EDIT: I had previously suggested linking directly to the unofficial Flathub distribution, but that may not be the best immediate solution to the problems I’m describing. I may rewrite this issue more substantially depending on what feedback I get, here and elsewhere.

## Is your feature request related to a problem? Please describe.
The [existing install instructions](https://element.io/get-started) for Element Desktop on Linux are not terribly user friendly. They require using the command line, and Element Desktop isn't otherwise available on official PPAs immediately accessible through GNOME Software, KDE Discover, and the like. Element Desktop is also not officially available on Linux distributions other than Debian or Ubuntu.

## Describe the solution you'd like
There is [an unofficial Element Desktop Flatpak on Flathub](https://flathub.org/apps/details/im.riot.Riot). The ["Get Started" page on Element.io](https://element.io/get-started) could include a link to the Flathub.org page, with a disclaimer along the lines of
> *the Flathub version of Element Desktop is not officially supported; for issues please contact the Flatpak maintainers*

and [a link to the Flathub build repo issue tracker](https://github.com/flathub/im.riot.Riot/issues).

Alternately, Element could "adopt" the unofficial Flatpak and take on responsibility supporting its users. Doing so would fix [issue vector-im/element-desktop#656](https://github.com/vector-im/element-desktop/issues/656) and make everything a lot easier for end users (albeit at the expense of additional developer resources). Regardless, it's worth considering the feasibility of this alternative.

## Describe alternatives you've considered
Considering this feature request is for a change to the Element.io website (or a change in Element's corporate policy, i.e. adopting the Flathub Flatpak), the main alternative would be the status quo. Adding a link to the unofficial Flathub Flatpak with a disclaimer that it's not officially supported is already the easier alternative.

I suppose the website could offer a shell script that encapsulates the existing shell command, but if it needs to be manually flagged as executable it might not be much more user-friendly than what's already there.

Probably the least intensive alternative would be adding a JavaScript to provide a button on the website to copy the existing shell commands into the user's clipboard in a single string.

## Additional context
Incidentally, scrolling is broken in the floating `<div>` on this page, at least on Firefox, and also there isn't a way to permalink the Linux install instructions:

<img width="1024" alt="Element Desktop Linux Installation" src="https://user-images.githubusercontent.com/9206310/118550516-c49c0200-b72a-11eb-9b48-8a350ede5ddd.png">

**Comment by aaronraimist** [comment]
I would not be opposed to adding a sentence like "The community maintains packages for other distributions" or something but I do not think the website should link to those packages. People already think the Flathub package is official. If it is linked to by the official website they will think that even more. People don't read all of the words, they just skip right over "unofficial".

If the Flathub package worked exactly the same as the official app then maybe it should be linked to but it doesn't. For example the Flathub package doesn't currently support searching encrypted messages https://github.com/flathub/im.riot.Riot/issues/123 which is one of the main reasons to install the desktop app over just using Element in a browser.

**Comment by elsiehupp** [comment]
> I would not be opposed to adding a sentence like "The community maintains packages for other distributions" or something but I do not think the website should link to those packages. People already think the Flathub package is official. If it is linked to by the official website they will think that even more. People don't read all of the words, they just skip right over "unofficial".

I just did [a pull request](https://github.com/flathub/im.riot.Riot/pull/180) adding a disclaimer to the Flathub, if that helps. (There wasn’t one previously.)

> If the Flathub package worked exactly the same as the official app then maybe it should be linked to but it doesn't. For example the Flathub package doesn't currently support searching encrypted messages [flathub/im.riot.Riot#123](https://github.com/flathub/im.riot.Riot/issues/123) which is one of the main reasons to install the desktop app over just using Element in a browser.

Yes, hence why it would be preferable if the Element maintainers were able to devote the resources to fixing those problems. Or, you know, otherwise making the Linux version installable without using the command line.

**Comment by elsiehupp** [comment]
By the way, thank you for the explanation. Given the major breaking limitations of the unofficial Flatpak, I can see why it would be a problem to encourage end users to download it instead.

That said, there are other ways that the Linux onboarding process could be made slightly more user-friendly given the circumstances.

**Comment by salim-b** [comment]
> For example the Flathub package doesn't currently support searching encrypted messages flathub/im.riot.Riot#123 which is one of the main reasons to install the desktop app over just using Element in a browser.

It [seems to work](https://github.com/flathub/im.riot.Riot/issues/123#issuecomment-844395812) as of recently thanks to [matrix-react-sdk#5806](https://github.com/matrix-org/matrix-react-sdk/pull/5806), at least it does for me now (Flatpak Element 1.7.28 on Ubuntu 20.04).
