### ISSUE TITLE
element.io issues

### ISSUE THREAD

**Issue by 532910** [vector-im/element.io#2]
1. https://element.io/get-started
There no relations between OS and button color:
![image](https://user-images.githubusercontent.com/14617699/88121382-42a48080-cbce-11ea-9de1-aac6eb25445e.png)

2. https://element.io/element-consulting
The button with shorter text is larger that the button with longer text. Button must have the same size:
![image](https://user-images.githubusercontent.com/14617699/88121378-3e786300-cbce-11ea-9c3c-2c854a7fb734.png)

3. The button with shorter text is larger that the button with longer text. Button must have the same size:
![image](https://user-images.githubusercontent.com/14617699/88121410-4f28d900-cbce-11ea-95b9-3a7e4b577454.png)

4. Unreadable text on https://element.io/blog :
![image](https://user-images.githubusercontent.com/14617699/88121432-5c45c800-cbce-11ea-8dc4-258d53e752ac.png)

5. Button has different size and alignment:
![image](https://user-images.githubusercontent.com/14617699/88121445-62d43f80-cbce-11ea-9e2b-9da367853e63.png)
![image](https://user-images.githubusercontent.com/14617699/88121462-6c5da780-cbce-11ea-8fbc-2083722e2ceb.png)
![image](https://user-images.githubusercontent.com/14617699/88121465-6ec00180-cbce-11ea-87ea-e08d9df9e313.png)

**Comment by JordanConnor** [comment]
Thanks for reporting :)
