### ISSUE TITLE
"What is Key Backup?" answer is wrong

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element.io#20]
> When key backup is enabled, your device will maintain a secure copy of its keys on our server.

Makes it sound like the backup is going to an Element server, rather than the user's homeserver

**Comment by t3chguy** [comment]
The next line is no better:

> Is it safe to back up my encryption keys to **your** servers?
> Yes. Your keys are encrypted before they are uploaded to our servers, so we never see them unencrypted.

**Comment by JordanConnor** [comment]
I believe these were amened sometime ago, but not mentioned here.

Did these updates solve the issues?
<img width="569" alt="Screenshot 2023-10-10 at 14 21 32" src="https://github.com/vector-im/element.io/assets/87339233/2c7919fc-8c79-4262-8aa8-f775ec334e1a">
<img width="600" alt="Screenshot 2023-10-10 at 14 21 15" src="https://github.com/vector-im/element.io/assets/87339233/aac131aa-08da-40f0-8235-cf61766609d4">

**Comment by aaronraimist** [comment]
@JordanConnor my comment has been fixed but part of @t3chguy's comment appears to still be a valid concern.

I would suggest modifying the answers to use something closer to these phrases:

- "Yes. Your keys are encrypted before they are uploaded to your Matrix homeserver, so only you can see them unencrypted." or "Yes. Your keys are encrypted before they are uploaded to your Matrix homeserver, so no one except you can see them unencrypted."

- "It is important to understand that to protect your privacy, your keys never leave your device unencrypted."

**Comment by JordanConnor** [comment]
Thanks for the suggestions @aaronraimist. I'll get those added :)

<img width="583" alt="Screenshot 2023-10-11 at 10 35 42" src="https://github.com/vector-im/element.io/assets/87339233/cf012a27-8c3a-4c7e-94c1-54ab64cee9a8">
<img width="566" alt="Screenshot 2023-10-11 at 10 37 17" src="https://github.com/vector-im/element.io/assets/87339233/dc4f7827-e607-491c-b0a3-38576ed71604">
