### ISSUE TITLE
 NoScript XSS Warning

### ISSUE THREAD

**Issue by Mikaela** [vector-im/element.io#22]
**Describe the bug**

I went to https://element.io/blog/spaces-the-next-frontier/ backgrounded the tab for some time and got a warning fron NoScript.

**To Reproduce**
1. Go to https://element.io/blog/spaces-the-next-frontier/
2. Switch tab
3. Return to computer and see a NoScript XSS Warning

**Expected behavior**

I expect to not see NoScript warning me.

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/831184/120112976-009a8280-c181-11eb-834e-1869dbb2fe95.png)

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Browser: Firefox
 - Version: 88.0.1

**Additional context**

```
NoScript detected a potential Cross-Site Scripting attack

from [...] to https://element.io.

Suspicious data:

(URL) https://element.io/blog/content/images/2021/05/Spaces---Post-Image.png
```

**Comment by JordanConnor** [comment]
I'm not able to replicate this, is it still an issue for you?
