### ISSUE TITLE
Contact Us page only links to #element-web:matrix.org

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element.io#23]
It doesn't have any links to the rooms for the mobile apps. Maybe this is one of the reasons why tons of people assume #element-web:matrix.org is the room for all Element apps.

https://matrix.to/#/!YTvKGNlinIzlkMTVRl%3Amatrix.org/%24Ev89AQ_mVIMCkDgvdAiZY5w9DdjCES_RgN5MoZVRees

**Comment by JordanConnor** [comment]
Improved with options on [/help](https://element.io/help) :)
<img width="1240" alt="Screenshot 2022-07-08 at 16 25 47" src="https://user-images.githubusercontent.com/87339233/178022926-ec43de8c-5174-4a2d-9439-843cfccee298.png">
