### ISSUE TITLE
IdentityServer privacy notice page links to a wrong Balsamiq docs link

### ISSUE THREAD

**Issue by tcitworld** [vector-im/element.io#24]
On the bottom of [this page](https://element.io/is-privacy-notice), there's a link to the document which inspired the IdentityServer terms of service, but it now redirects to [some user docs](https://media.balsamiq.com/img/support/docs/myb/mybalsamiq_docs.pdf). The correct link is https://balsamiq.com/legal/terms/tos/.

**Comment by JordanConnor** [comment]
Thank you for reporting. We have since changed this [document](https://element.io/identity-server-privacy-policy)
