### ISSUE TITLE
Pricing callout tabs lack left/right padding

### ISSUE THREAD

**Issue by DiscRisknBisque** [vector-im/element.io#25]
Currently text runs to the edge of callout tabs on the pricing page. Applying `padding: 10px 15px` doesn't break any responsive styling and overall looks good to me.
![image](https://user-images.githubusercontent.com/3990373/127206500-2d7c8609-ab4d-473e-8caa-eea0608613b8.png)

**Comment by callahad** [comment]
I suspect the intended design to to have the tab stretch the full width of the box, like in the mobile layout:

> ![Screen Shot 2021-08-03 at 21 03 11](https://user-images.githubusercontent.com/24193/128078684-d549954e-360e-4e0d-a9c2-dd225e58a19e.png)

It looks like the site is achieving this with flexbox and `align-items: stretch`, but that property isn't applied to the desktop layout:

> ![Screen Shot 2021-08-03 at 21 04 26](https://user-images.githubusercontent.com/24193/128078795-7d66cf62-1680-42b6-9977-4db10d10e1fa.png)

The same issue also manifests on the "Personal" tab:

> ![Screen Shot 2021-08-03 at 21 04 52](https://user-images.githubusercontent.com/24193/128078876-a017d8a4-9326-472f-b09e-a81dae6fead9.png)

cc: @nadonomy

**Comment by JordanConnor** [comment]
Thanks for the report, have a fix ready for the next deployment.
