### ISSUE TITLE
Going to "Compare all EMS Plans"  causes Firefox HTTPS-Only Mode to issue the error "Secure Connection Not Available"

### ISSUE THREAD

**Issue by rtanglao** [vector-im/element.io#28]
**Describe the bug**

Going to "Compare all EMS Plans"  causes Firefox HTTPS-Only Mode to issue the error `Secure Connection Not Available`

**To Reproduce**
1. Go to Firefox Settings at `about:preferences#privacy` and Tick `Enable HTTPS-Only Mode in all windows`
2. Clickpath: : `Element (home page)` > `Products` > `Element Matrix Services` > `Compare all EMS Plans` 
4. See error in screenshot

**Expected behavior**

With the default setting in Firefox settings  of
`Don't enable HTTPS-Only mode` this  problem doesn't occur

**Screenshots**
![image](https://user-images.githubusercontent.com/45195/131881869-260b591a-1ec4-4473-a19a-634befce061f.png)

**Desktop (please complete the following information):**
 - Device: Dell XPS 13 9310
 - OS: Ubuntu 20.04
 - Browser [e.g. stock browser, safari] Firefox 93.0a1 (2021-09-02) (64-bit)
 - Version [e.g. 22] 93

**Additional context**
* For those with access here is the support ticket from the EMS customer  https://newvector.zammad.com/#ticket/zoom/19156
* @JordanConnor was able to reproduce this issue

**Comment by JordanConnor** [comment]
The path and a redirect may be the issue

The button URL seems like it's redirecting:   `/plans-and-pricing/(.*) `  **-->**    `/pricing/%1`
Where 'capture group' `%1` isn't found in the `/pricing page` (HTTPS only might see this as insecure?)

**I've changed the page button to direct to correct page** in the next deployment, be aware of any other pages.
