### ISSUE TITLE
Misaligned icons in "get started" section -> desktop

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element.io#30]
![image](https://user-images.githubusercontent.com/22740616/140373917-35eeb30d-1e35-4dd9-a9b0-3143085cab87.png)

Browser: Brave `Version 1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)`
OS: Linux Pop_OS 21.04

**Comment by JordanConnor** [comment]
Thanks. Alignment should have been fixed :)
