### ISSUE TITLE
(nit) Linux install instructions not in monospace font

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element.io#31]
![image](https://user-images.githubusercontent.com/22740616/140374310-f0c1f184-8b59-4b6d-a629-2dd2783c4492.png)

**Comment by ShadowJonathan** [comment]
Note that the current latest instructions kinda look like this;

![](https://user-images.githubusercontent.com/87339233/160615437-76252b40-b54d-481a-ac42-46b73374c5fc.png)

**Comment by JordanConnor** [comment]
It would be a nice touch to revisit if there's no preformance impact. Thanks for the suggestion!
