### ISSUE TITLE
Add install instructions for Flatpak in Linux section

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element.io#32]
https://flathub.org/apps/details/im.riot.Riot exists, and as far as I know is controlled by Element itself, it'd be helpful if install instructions are also included in the linux section.

**Comment by aaronraimist** [comment]
It is not controlled by Element. It is community maintained. https://github.com/flathub/im.riot.Riot/issues/87

**Comment by ShadowJonathan** [comment]
Alright, then this issue is mostly undefined, then it depends on if unofficial packages should be promoted in an official site.

**Comment by aaronraimist** [comment]
Is it intentional that it now *only* links to the unofficial flatpak and doesn't link to the official debian/ubuntu package?

**Comment by ShadowJonathan** [comment]
(iirc there was work ongoing to make that unofficial flatpak into an official one?)

**Comment by JordanConnor** [comment]
Debian was inadvertantly removed, fixing this in an upcoming [deployment](https://github.com/vector-im/element.io/issues/51#issuecomment-1081835691) :)
