### ISSUE TITLE
We no longer have free EMS trials so please remove Free Trial Mention at https://element.io/element-matrix-store

### ISSUE THREAD

**Issue by rtanglao** [vector-im/element.io#34]
We no longer have free EMS Trials so please remove the mention of Free Trials on our matrix-store page at:
https://element.io/element-matrix-store

Screenshot of what should be removed from that page:
![image](https://user-images.githubusercontent.com/45195/142481554-0a4f938b-1743-41ca-b734-4984f9b9a84d.png)

**Comment by steveloynes** [comment]
Hi @JordanConnor just checking you've seen this. Thanks!

**Comment by JordanConnor** [comment]
Thanks, was removed :)
