### ISSUE TITLE
Help page mentions key share dialog which no longer exists

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element.io#39]
https://element.io/help#encryption9 says

> How do I request the key from another device via key share?

> When Element sees a message it can't decrypt, it automatically asks your other devices if they have a copy of the necessary key. Keys will be shared automatically with trusted devices - **if the device with the key hasn't trusted the device requesting the key, the device with the key will pop up a prompt asking you to confirm the key share manually**.

As far as I know the part I have put in bold is no longer true and should be removed. See https://github.com/vector-im/element-web/issues/17670 https://github.com/vector-im/element-web/issues/11904 https://github.com/vector-im/element-web/issues/11908

**Comment by richvdh** [comment]
Also, https://element.io/help#encryption4 says:

> If your device doesn't have the right key, there are three ways you might be able to get hold of the key:
>
> Restore all of your keys from key backup
> Request the specific key from another device via key share
> Upload keys from a manual backup (advanced)

There is no longer any way to actively request a key, so this is somewhat misleading.

**Comment by JordanConnor** [comment]
Thanks. These should both be amended in a coming update to the page:

<img width="617" alt="Screenshot 2023-10-10 at 14 17 13" src="https://github.com/vector-im/element.io/assets/87339233/2f199975-3d6f-40bf-8913-d0e0393427cc">
<img width="611" alt="Screenshot 2023-10-10 at 14 16 38" src="https://github.com/vector-im/element.io/assets/87339233/05eb6c29-fdef-403d-b9a6-bdc98d4be442">
