### ISSUE TITLE
Setup a Matrix server on element.io and use it for main room aliases

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element.io#4]
**Describe the solution you'd like**
I think there should be a private Matrix server on element.io and element.io addresses should be used for the main addresses on the Element rooms.

This does a couple of things. For one it would just look nice to have aliases like #android:element.io, #web:element.io, #dev:element.io, etc. It gives the user some confidence that it is an official room. Additionally it lets you search the element.io room directory to find all of the related rooms.

Another big thing it does is help to teach users that matrix.org is not the only server that exists.

**Additional context**
I have mentioned this a few times in various rooms but it always seems to get lost so adding an issue here to track it.

**Comment by aaronraimist** [comment]
@JordanConnor any reasoning behind closing this?

**Comment by turt2live** [comment]
The server exists and we've started using it for some rooms.

**Comment by aaronraimist** [comment]
Ah awesome. Haven't seen it yet but I look forward to Web, iOS, and Android getting new aliases.
