### ISSUE TITLE
"Connect with anyone" jigsaw graphic does not animate together

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element.io#40]
The jigsaw graphic in the "Connect with anyone" section seems a bit awkward like it should connect the pieces to the middle Element logo but it never comes together as you scroll down the page.

https://element.io/personal

![](https://user-images.githubusercontent.com/558581/151084034-a6cf604f-b795-49e5-80de-0d7462ff61ee.gif)

**Comment by JordanConnor** [comment]
It did meet, but didn't work responsively. Will look to update this when we revisit this page, thank you for the suggestions :)
