### ISSUE TITLE
Grid of "Most recent" posts has one mis-aligned below the rest

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element.io#41]
Grid of "Most recent" posts has one mis-aligned below the rest.

Page: https://element.io/blog/

Tested in Chrome and Firefox

![](https://user-images.githubusercontent.com/558581/153079178-4060a3fb-c5b1-4c20-8bfc-a66ce10b10c9.png)

**Comment by MadLittleMods** [comment]
Also the grids are all messed up when viewing a specific tag/category.

https://element.io/blog/tag/whats-new/

![](https://user-images.githubusercontent.com/558581/153080151-ea962272-3af2-483c-9a6c-5e215b095dac.png)

**Comment by JordanConnor** [comment]
The grid appears to have been initially implemented in an odd way, flex wrap seems much better. Should be resolved now, thanks! :)
