### ISSUE TITLE
No way to actually "See all posts"

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element.io#42]
I want to see the full backlog of blog posts we've made but it doesn't seem possible. The "See all posts" link in the header just redirects me to the same page I am on so I can only view the 6 most recent blog posts.

https://element.io/blog/

![](https://user-images.githubusercontent.com/558581/153079737-0f5827c8-bd55-41e8-92c1-f4c95062dc51.png)

**Comment by JordanConnor** [comment]
The blog will soon be given a much-needed refresh to address this and other issues 🙌

**Comment by MadLittleMods** [comment]
The blog now supposedly shows all posts on https://element.io/blog/ which goes back to 2019. It's unclear if that is the first post though.
