### ISSUE TITLE
Avatars missing from testimonial quotes on careers page

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element.io#43]
Avatars missing from testimonial quotes on careers page.

https://element.io/careers

![](https://user-images.githubusercontent.com/558581/153161930-2b282862-3861-4524-84b7-91fb8c77f5f0.png)

**Comment by JordanConnor** [comment]
I can't seem to replicate this 🤔 
@MadLittleMods, might it be browser/setup specific? Any more details you can provide will help me find a fix

Thanks!

**Comment by MadLittleMods** [comment]
Try it in a fresh incognito Chrome on first load. It seems to work after refreshing the page. Maybe related to `loading="lazy"` stuff
