### ISSUE TITLE
Blog page on mobile is not properly scaled

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element.io#44]
![5A9E7743-66F0-4AC8-9FC8-C2EECDF6BFF1](https://user-images.githubusercontent.com/22740616/156782662-daa39278-7254-47d7-8c60-c4ae0ffa53fd.png)

This screen has margins on both sides, and way too small a font, I suspect something happened to the mobile scaling hint (in the head tag).

**Comment by JordanConnor** [comment]
Thanks for reporting :)
There's a few updates we're planning like to improve the blog.

What device was this on?

**Comment by ShadowJonathan** [comment]
iPhone 11, but I already discovered why this is; I had the element.io website set to 50% zoom 🤦

Sorry, my bad!
