### ISSUE TITLE
Attempting to report abuse fails to report, instead it attempts to log in as `abuse` at matrix.org.

### ISSUE THREAD

**Issue by grahamperrin** [vector-im/element.io#45]
**Describe the bug**

A click on 'contact' to report abuse results in an inappropriate attempt to log in as user `abuse` at `http://matrix.org./`

**To Reproduce**

1. <https://element.io/help>
2. Scroll down to 'How do I submit an abuse report?', _To report an abuse issue on the Matrix.org homeserver please contact._
3. click the linked phrase `contact.` – nb the `.` at the tail.

> You are about to log in to the site “matrix.org.” with the username “abuse”, but the web site does not require authentication. This may be an attempt to trick you.
> 
> Is “matrix.org.” the site you want to visit?

It is _not_, however I was curious about the effect of clicking **Yes**. Result: 

* `https://matrix.org./` 

**Expected behavior**

I guess, `mailto:abuse@matrix.org`

**Screenshots**

![image](https://user-images.githubusercontent.com/192271/157889706-225a0e3b-0daf-4afa-a651-28db0c7d5dbf.png)

**Desktop (please complete the following information):**
 - OS: FreeBSD 14.0-CURRENT	
 - Browser: Firefox
 - Version: 98

**Comment by JordanConnor** [comment]
Thanks for reporting :)

The mailto link should now work as intended, made an issue to fix full stop
