### ISSUE TITLE
Element on Linux - Fedora/CentOS package discontinued

### ISSUE THREAD

**Issue by pschloenzke** [vector-im/element.io#46]
[https://element.io/get-started#linux](https://element.io/get-started#linux) leads Fedora and CentOS users to enable a copr repository which is no longer maintained. Packages have been withdrawn, installation is no longer possible.
See the shutdown notice: [https://copr.fedorainfracloud.org/coprs/taw/element/](https://copr.fedorainfracloud.org/coprs/taw/element/)

**Comment by JordanConnor** [comment]
Thanks. It should now display the correct Community built package and instructions :)
