### ISSUE TITLE
Linux instructions

### ISSUE THREAD

**Issue by JordanConnor** [vector-im/element.io#51]
Currently we link to [flathub](https://flathub.org/apps/details/im.riot.Riot), previously we had a dialog with various instructions (replaced as it was outdated). 
**What instructions would cater to the whole Linux community?**

**Comment by turt2live** [comment]
Where was the discussion about the dialog being outdated?

**Comment by SimonBrandner** [comment]
This does seem very wrong as it sends you to flathub (an unofficial source) even on Debian where we have an official repo

**Comment by JordanConnor** [comment]
Are these Debian instructions still valid? If so i can restore these in the next deployment :)

**Debian / Ubuntu 64 bit systems:**
```
sudo apt install -y wget apt-transport-https
‍
sudo wget -O /usr/share/keyrings/element-io-archive-keyring.gpg https://packages.element.io/debian/element-io-archive-keyring.gpg
‍
echo "deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main" | sudo tee /etc/apt/sources.list.d/element-io.list
‍
sudo apt update
‍
sudo apt install element-desktop
```

Is there anything else that should be included?

**Comment by SimonBrandner** [comment]
From a quick look, they seem valid. Is there something that happened that made you think they were not?

**Comment by JordanConnor** [comment]
It was communicated that Fedora and CentOS packages are discontinued, with which the Debian instructions were inadvertantly removed. I shall have these restored soon :)

**Comment by turt2live** [comment]
Thank you! and yes, Fedora+CentOS are no longer available, sadly.

**Comment by JordanConnor** [comment]
Here's the proposed Linux section including Debian instructions, a mention of community packages and the flathub link, is this clear and helpful? :)

<img width="1205" alt="Screenshot 2022-03-29 at 13 49 05" src="https://user-images.githubusercontent.com/87339233/160615437-76252b40-b54d-481a-ac42-46b73374c5fc.png">

**Comment by ShadowJonathan** [comment]
Nit; these command line instructions are not in monospace, that's what https://github.com/vector-im/element.io/issues/31 was about, which I assume was closed because there were no more Linux instructions like this.

The reason I think this is important is because it's some "trust flag" for any tech savvy user, if it's not in monospace, then people are going to squint harder, because they assume that the people behind the project don't "get it", as Linux has always been played as second-citizen to them, in manners like this.

**Comment by turt2live** [comment]
@JordanConnor lgtm - can we get it out relatively urgently and do iteration as needed?

**Comment by ShadowJonathan** [comment]
(In that case, could #31 be reopened?)

**Comment by dbkr** [comment]
I think we need to understand what went wrong here & what's holding this up - currently there's just no way to download the Linux version of our own desktop app from our own website.

**Comment by JordanConnor** [comment]
This iteration is now [deployed](https://github.com/vector-im/element.io-website/pull/31)!
I'd happy to flag any future linux changes for review with more context :)

**Comment by SimonBrandner** [comment]
https://user-images.githubusercontent.com/25768714/162011853-99ae8b4a-16ab-4985-8470-6f95b5680537.mp4

element.io still seems to be doing something weird :/

**Comment by turt2live** [comment]
@SimonBrandner likely a caching issue (either locally or with cloudflare)

**Comment by SimonBrandner** [comment]
Ah, I can confirm it works now! :heart:
