### ISSUE TITLE
User guide: minor typos

### ISSUE THREAD

**Issue by mattcen** [vector-im/element.io#52]
Hey folks, I absolutely *love* the [user guide](https://element.io/user-guide)! I've been wanting a well-designed getting started guide for ages; thanks so much!

I've however noticed some typos and odd grammatical choices in it, which I've listed below.

Also, is there a plan for this to be available as a web page, or at least a PDF that has *actual* searchable text in it? It's really not accessible as it is.

pg 4:
```diff
-To learn more about homservers
+To learn more about homeservers
```
('homserver' missing 'e')

pg 6 (B. Device verification):
```diff
-Click the Avatar the person you would like to verify, in the room header or after clicking the information icon .
+Click the Avatar of the person you would like to verify, in the room header or after clicking the information icon.
```
(add 'of', and remove space before full-stop)
```diff
- a set of emoji's appear on screen.
+a set of emojis appear on screen.
```
I don't *think* "emoji's" should have an apostrophe?
(This recurs on pg 7, but is spelled without apostrophe on pg 17)

pg 8:
```diff
-at the top left, from there
+at the top left; from there
```
(replace comma with semicolon)

pg 9:
```diff
-Click this and you will be taken to your system"s
+Click this and you will be taken to your system's
```
(replace double-quote with single quote)
```diff
-Email addresses and phone numbers are optional, to reset your account or have forgotten your password.
+Email addresses and phone numbers are optional, but allow you to reset your account or recover a forgotten password.
```

pg 13:
```diff
-clicking on the alarm icon
+clicking on the bell icon
```
(stylistic choice, but seems like a more accurate description)

pg 16 (A. Room header):
```diff
-Start a video or audio call when you're in a room or coversation by
+Start a video or audio call when you're in a room or conversation by
```
('coversation' missing the 'n')

pg 21:
```diff
-room name on iOS and android
+room name on iOS and Android
```
(capitalise Android)

pg 22
> Manage widgets, bridges and bots are optional advanced extras

Feels like an awkward sentence; perhaps remove "Manage?"

pg 23:
> That's your whistle stop quick start user guide!

"whistle stop?" Is this a phrase I'm just unfamiliar with, or is it a typo? "one-stop?"

---

Also, none of the things that look like links in the document are actually clickable.

Sorry for all the corrections! Trying to walk the line between not being too pedantic, but also wanting to improve a document that I really would love to share with people because it's so well-formatted and comprehensive!

(Tagging @JordanConnor as the PDF author)

**Comment by aaronraimist** [comment]
I second the request for the text to be searchable/selectable and for hyperlinks to work.

Also wanted to point out the copyright notice on page 7 clips into the image

<img width="440" src="https://user-images.githubusercontent.com/5855073/160297703-ccce06a9-5d6d-4a26-bbd1-d2e7a075be96.png">

**Comment by JordanConnor** [comment]
Thank you for listing the typos and suggestions!
These should now be updated in the [document](https://static.element.io/pdfs/element-user-guide.pdf), which is now searchable and selectable 😃
