### ISSUE TITLE
Can't make voice call

### ISSUE THREAD

**Issue by astral-shining** [vector-im/element.io#57]
I can't make voice call, is making a jitsi call instead. For some reason worked first time I pressed it but now keeps making a jitsi call when I press the voice call button

Am using element web 
Element version: 1.10.14
Olm version: 3.2.8

**Comment by JokerGermany** [comment]
Are in the room more than two mxids?

**Comment by astral-shining** [comment]
> Are in the room more than two mxids?

yes I am

**Comment by JokerGermany** [comment]
In a room with more then 2 mxids, a jitsi call is started.
At the moment a normal voice chat is only possible between 2 mxids.

This will change in the future. At the moment it is tested with [element call](https://call.element.io/) which will be integrated in element later.
https://element.io/blog/introducing-native-matrix-voip-with-element-call/

**Comment by astral-shining** [comment]
I have my own element server with matrix synapse, when I do those calls am using call.element.io? or only using my server?

**Comment by SimonBrandner** [comment]
I am going to close this as this should have been submitted at https://github.com/vector-im/element-web. Also, in the end, this does not seem to be an issue but rather a support question - for that please visit [#element-web:matrix.org](https://matrix.to/#/#element-web:matrix.org)
