### ISSUE TITLE
Attachment Download in Element Desktop Snap Version not working

### ISSUE THREAD

**Issue by kaminski** [vector-im/element.io#59]
**Describe the bug**
The attachment download button does not open the file manager or react in any other way. So attachments can't be accessed at all. However, the file manager does appear when adding attachments to a conversation.    

**To Reproduce**
1. In Element Desktop Snap Version open any conversation with an attachment in the timeline. 
2. Scroll to the attachment and attempt to download it with the arrow-down button to right of the attachment. 
3. The click event on the download button does not trigger anything. 

**Expected behavior**
Clicking on the download button (arrow down) to the right of an attachment in a conversation should open the file browser so I can specify where to save the attachment(s).

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - [Element Desktop Snap Version](https://snapcraft.io/element-desktop) 
 - Version Element version: 1.11.24 Olm version: 3.2.12 (As mentioned in Settings > Help & About)

**Comment by t3chguy** [comment]
This repo is for the element.io website only, the Snap is community maintained.
