### ISSUE TITLE
Fix Debian/Ubuntu install info

### ISSUE THREAD

**Issue by brianclinkenbeard** [vector-im/element.io#6]
gpg keys for packages should be placed in `/etc/apt/trusted.gpg.d` (the designated location for package gpg keys) instead of `/usr/share/keyrings`. This would also allow from the removal of the `[signed-by=...]` parameter.

These install instructions can be replaced:
```
sudo wget -O /usr/share/keyrings/riot-im-archive-keyring.gpg https://packages.riot.im/debian/riot-im-archive-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/riot-im-archive-keyring.gpg] https://packages.riot.im/debian/ default main" | sudo tee /etc/apt/sources.list.d/riot-im.list
```
With these:
```
sudo wget -O /etc/apt/trusted.gpg.d/riot-im-archive-keyring.gpg https://packages.riot.im/debian/riot-im-archive-keyring.gpg

echo "deb https://packages.riot.im/debian/ default main" | sudo tee /etc/apt/sources.list.d/riot-im.list
```
To resolve the issue.

**Comment by andrewshadura** [comment]
Hi,
What you’re suggesting is actually wrong: `/etc/apt/trusted.gpg.d` is deprecated and third-party keys should not be put there.
See https://wiki.debian.org/DebianRepository/UseThirdParty for more details.

I suggest this bug should be closed as *invalid*.

**Comment by brianclinkenbeard** [comment]
Interesting, I only went off the documentation suggesting the replacement of `apt-key`. Thank you for bringing this to my attention, apologies.
