### ISSUE TITLE
Website sets my laptop on fire

### ISSUE THREAD

**Issue by richvdh** [vector-im/element.io#60]
It looks shiny and all, but Firefox spinning at 200% CPU really isn't a thing that makes me want to use your product.

This is on Firefox 111.0 on Ubuntu 22.04.

**Comment by JordanConnor** [comment]
Thanks for your feedback. We're looking at a redesign which will address this :)

**Comment by JordanConnor** [comment]
This should be resolved with the newest designs, which are also due to be optimised in the next deployment :)
