### ISSUE TITLE
Login with GitHub etc. problem

### ISSUE THREAD

**Issue by whyghost** [vector-im/element.io#63]
A long time ago, I registered with my GitHub account in element.io for matrix, but now I don't want login with my GitHub account so I can't change the password etc. Can I remove GitHub integration in my account?

**Comment by JordanConnor** [comment]
Hi @whyGhosT, your issue might be better addressed in this repository: https://github.com/vector-im/element-web/issues (as this one mainly deals with the website and not the web app) 

Thanks!
