### ISSUE TITLE
E-Mail Verification for Admin Panel Account Creation not Working

### ISSUE THREAD

**Issue by Jayryn** [vector-im/element.io#68]
**Describe the bug**
Clicking the link in the sent Email by Element, when trying to verify the email for account creation in the admin panel, opens a blank page with no redirects and it does no verify the account email (which makes the account unusable).

**To Reproduce**
1. Go to 'https://element.io'
2. Click on 'Sign In' on the top right corner
3. Select 'Admin dashboard'
4. Click on 'Register'
5. Enter Details
6. Open Sent E-Mail Link for verification

**Expected behavior**
Clicking the link should verify and finish account setup.

**Screenshots**
<img width="599" alt="image" src="https://github.com/element-hq/element.io/assets/77808206/181f2f29-0d69-4c3a-95f2-e10cbc9befea">
<img width="1437" alt="Element Email Verification" src="https://github.com/element-hq/element.io/assets/77808206/8f524f0e-737c-4c2f-a95c-e30792c4b9ad">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma Version 14.4.1 (23E224)
 - Browser Safari (Version 17.4.1 (19618.1.15.11.14)) / Arc (Version 1.38.0 (48670), Chromium Engine Version 123.0.6312.123)

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 17.4.1
 - Browser Safari
 - Version Newest (But can't find the version number)

**Additional context**
No additional context.

**Comment by Twi1ightSparkle** [comment]
Does it work if you disable all your browser addons? Or in a different browser? For further support regarding your account specifically, please email us at  `ems-support@element.io`

**Comment by Jayryn** [comment]
> Does it work if you disable all your browser addons? Or in a different browser? For further support regarding your account specifically, please email us at  `ems-support@element.io`

I tried it on the Arc Browser (Chromium Based) aswell. I tried it on Windows a few days later and it worked there (so my account is verified now but this could be an issue that should probably still be addressed, if someone is able to reproduce this).

As far as extensions go on Safari, I don't use any additional Adblock or anything on Mac and iOS (except the Lockdown App, which should only block some known tracker domains as of my knowledge)

**Comment by Twi1ightSparkle** [comment]
I'm also unable to reproduce on macOS Sonoma/Safari with [lockdown mode](https://support.apple.com/en-us/105120) enabled. I recommend you exclude our website from the Lockdown app. We do not serve ads and self-host our analytics and do it as privacy-preserving as possible (https://element.io/privacy).

If you are able to reliably reproduce without any apps or addons blocking/modifying connections, please re-open the issue with exact steps.
