### ISSUE TITLE
Make "Also available on Linux" working without JavaScript

### ISSUE THREAD

**Issue by xundeenergie** [vector-im/element.io#7]
**Is your feature request related to a problem? Please describe.**
I have "noscript" activated on all my browsers for several security-reasons. On elements.io nothing happens on a click to "Also available on linux"... so i was misleading on my search for a desktop-app in fedora. no hint that riot is now called element, what to search about, and so on. And it is frustrating to get shown "Linux... yes it exists, but we don't care about you"

**Describe the solution you'd like**
A click on "Also available on Linux" should open a popup or new Window with the information you get, with enabled javascript as well. 

**Describe alternatives you've considered**
It would be even nice, to give the Linux-link the same color and presence as the two buttons for mac and windows have...

**Comment by JordanConnor** [comment]
Thanks. We made some progressive improvements previously and now Linux is also visible by default in the latest deployment
