### ISSUE TITLE
Link to Linux tarballs

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element.io#70]
in addition to the deb repo

https://packages.element.io/desktop/install/linux/index.html

**Comment by JordanConnor** [comment]
How should this be shown? `Tarballs` link under the `Debian / Ubuntu x86_64 / aarch64` code, or add it to the community list?
<img width="593" alt="Screenshot 2024-06-17 at 11 28 20" src="https://github.com/element-hq/element.io/assets/87339233/69c3a7f1-397f-4032-b5f9-17478044df97">

**Comment by t3chguy** [comment]
They're first party not community. As for the link text: this is fine, we can iterate later
