### ISSUE TITLE
Community maintained packages

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element.io#71]
`Community maintained packages` should be below the official package/s to avoid confusion as the deb repo being listed under the banner of community maintained, as it is first party

**Comment by JordanConnor** [comment]
Good point, i'll swap the order

<img width="591" alt="Screenshot 2024-06-17 at 11 29 33" src="https://github.com/element-hq/element.io/assets/87339233/def7904a-e116-4800-9b06-21f920817cc2">

**Comment by t3chguy** [comment]
Perfect, thanks
