### ISSUE TITLE
Clicking the site logo on the blog does nothing

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element.io#8]
![image](https://user-images.githubusercontent.com/1342360/102511515-caf55780-4080-11eb-98ac-5d3448fc0dce.png)

## To reproduce

1. Head to any blog post, such as https://element.io/blog/announcing-the-element-public-roadmap/
2. Try to click the "Element blog" logo in the top left
3. Nothing happens. Looks like it's currently the default hyperlink to `#` and hasn't been changed yet.

I believe it should do the same as the "See all posts" button. It shouldn't take you back to https://element.io as there's already a nice big button in the top right to do that.

**Comment by JordanConnor** [comment]
Goes back to the main website :)
